postsubmits:
  - name: post-banka-2-backend-build
    always_run: true
    decorate: true
    max_concurrency: 1
    labels:
      preset-harbor-robot-push: "true"
      preset-k8s-banka-2: "true"
    spec:
      containers:
        - image: harbor.k8s.elab.rs/base-images/base:java-17-node-18-docker
          command:
            - /bin/bash
            - -c
            - |
              set -euo pipefail

              cd ..
              git clone https://github.com/RAF-SI-2023/Banka-2-Infrastructure.git ./Banka-2-Infrastructure

              cd ./Banka-2-Infrastructure
              echo "BACKEND_ABSOLUTE_PATH=/home/prow/go/src/github.com/RAF-SI-2023/Banka-2-Backend" > .env 
              echo "FRONTEND_ABSOLUTE_PATH=/home/prow/go/src/github.com/RAF-SI-2023/Banka-2-Frontend" >> .env
              echo "INFRASTRUCTURE_ABSOLUTE_PATH=/home/prow/go/src/github.com/RAF-SI-2023/Banka-2-Infrastructure" >> .env

              cd ../Banka-2-Backend
              TEAM_NAME="banka-2"

              start-docker.sh
              docker login -u $HARBOR_USERNAME -p $HARBOR_PASSWORD harbor.k8s.elab.rs
              commit_hash=$(git rev-parse HEAD)

              for serviceName in bank-service iam-service notification-service stock-service otc-service; do
                docker build -f "../Banka-2-Infrastructure/images/${serviceName}.Dockerfile" -t harbor.k8s.elab.rs/${TEAM_NAME}/${serviceName}:latest "$serviceName"

                docker tag harbor.k8s.elab.rs/${TEAM_NAME}/${serviceName}:latest harbor.k8s.elab.rs/${TEAM_NAME}/${serviceName}:${commit_hash}

                docker push harbor.k8s.elab.rs/${TEAM_NAME}/${serviceName}:latest
                docker push harbor.k8s.elab.rs/${TEAM_NAME}/${serviceName}:${commit_hash}
              done
              
              helm upgrade --namespace="$TEAM_NAME-dev" --create-namespace --timeout=20m --atomic --install --set imageTag="${commit_hash}" "$TEAM_NAME-backend" "oci://harbor.k8s.elab.rs/$TEAM_NAME/$TEAM_NAME-backend/$TEAM_NAME-backend"
              if [ "$PULL_BASE_REF" == "main" ]; then
                helm upgrade --namespace="$TEAM_NAME-prod" --create-namespace --timeout=20m --atomic --install --set imageTag="${commit_hash}",host="$TEAM_NAME.si.raf.edu.rs" "$TEAM_NAME-backend" "oci://harbor.k8s.elab.rs/$TEAM_NAME/$TEAM_NAME-backend/$TEAM_NAME-backend"
              fi
          securityContext:
            privileged: true
          imagePullPolicy: Always
