version: '3.8'
services:
  postgres-db:
    image: postgres
    container_name: bank_db
    environment:
      POSTGRES_DB: bank_db
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d bank_db" ]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis
    expose:
      - "6379"
    container_name: redis
    environment:
      REDIS_HOST_AUTH_METHOD: trust
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: my-rabbit-host
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./rabbitdata:/var/lib/rabbitmq"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 20s
      retries: 5

  bank-service:
    build: ./BankService
    container_name: bank-service
    ports:
      - "8003:8003"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/bank_db?currentSchema=bank_service_schema
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      postgres-db:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  iam-service:
    build: ./IAMService
    container_name: iam-service
    ports:
      - "8000:8000"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/bank_db?currentSchema=iam_service_schema
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      postgres-db:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  notification-service:
    build: ./NotificationService
    container_name: notification-service
    ports:
      - "8002:8002"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/bank_db?currentSchema=notification_service_schema
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on: #conditions for service to start, its a black magic dont touch unless u know what u are doing!
      rabbitmq:
        condition: service_healthy

  stock-service:
    build: ./StockService
    container_name: stock-service
    ports:
      - "8001:8001"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/bank_db?currentSchema=stock_service_schema
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_REDIS_HOST=redis
    depends_on:
      postgres-db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started

  otc-service:
    build: ./OTCService
    container_name: otc-service
    ports:
      - "8004:8004"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/bank_db?currentSchema=otc_service_schema
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      postgres-db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
